name: Deploy test

on:
  repository_dispatch:
    types: [start-xray]
  workflow_dispatch:

jobs:
  run-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Config Folder
        run: mkdir -p ./xray-config

      - name: Write Xray Config
        run: |
          cat <<EOF > ./xray-config/config.json
          {
            "log": { "loglevel": "info" },
            "dns": {
              "servers": ["localhost", "1.1.1.1"]
            },
            "reverse": {
              "bridges": [{"tag": "github-bridge", "domain": "tunnel.github.internal"}]
            },
            "outbounds": [
              {
                "tag": "tunnel-to-core",
                "protocol": "vless",
                "settings": {
                  "vnext": [{"address": "${{ secrets.DOMAIN }}", "port": 443, "users": [{"id": "${{ secrets.UUID }}", "encryption": "none"}]}]
                },
                "streamSettings": {
                  "network": "ws",
                  "security": "tls",
                  "tlsSettings": {"allowInsecure": false, "serverName": "${{ secrets.DOMAIN }}"},
                  "wsSettings": {"path": "/edge", "headers": { "Host": "${{ secrets.DOMAIN }}" }},
                  "sockopt": { "tcpKeepAliveIdle": 15, "tcpKeepAliveInterval": 5 }
                },
                "mux": { "enabled": true, "concurrency": 8 }
              },
              { 
                "tag": "out-direct", 
                "protocol": "freedom",
                "settings": { "domainStrategy": "AsIs" }
              },
              { "tag": "block", "protocol": "blackhole" }
            ],
            "routing": {
              "domainStrategy": "AsIs",
              "rules": [
                { "type": "field", "domain": ["full:tunnel.github.internal"], "outboundTag": "tunnel-to-core" },
                { "type": "field", "outboundTag": "block", "domain": ["full:reverse", "regexp:.*\\\\.internal$"] },
                { "type": "field", "inboundTag": ["github-bridge"], "port": 53, "outboundTag": "out-direct" },
                { "type": "field", "inboundTag": ["github-bridge"], "outboundTag": "out-direct" }
              ]
            }
          }
          EOF

      - name: Run Xray
        run: |
          docker run -d --name xray-bridge \
            -v $(pwd)/xray-config:/etc/xray \
            teddysun/xray:24.11.30 \
            xray -config /etc/xray/config.json
          
          sleep 10
          docker logs -f xray-bridge &
          sleep 18000
